version: "3.7"

x-clickhouse-defaults: &clickhouse-defaults
  restart: unless-stopped
  image: yandex/clickhouse-server:22.1.3.7
  ulimits:
    nproc: 65535
    nofile:
      soft: 262144
      hard: 262144

services:
  clickhouse-blue-1:
    <<: *clickhouse-defaults
    container_name: clickhouse-blue-1
    hostname: clickhouse-blue-1
    ports:
      - 9000:9000
      - 8123:8123
      - 9181:9181
    volumes:
      - "/clickhousedb-data/clickhouse-blue-1/dataDir:/var/lib/clickhouse"
      - "./configs/gen/clickhouse-blue-1:/etc/clickhouse-server/config.d/"

  clickhouse-blue-2:
    <<: *clickhouse-defaults
    container_name: clickhouse-blue-2
    hostname: clickhouse-blue-2
    ports:
      - 9001:9000
      - 8124:8123
      - 9182:9181
    volumes:
      - "/clickhousedb-data/clickhouse-blue-2/dataDir:/var/lib/clickhouse"
      - "./configs/gen/clickhouse-blue-2:/etc/clickhouse-server/config.d/"

  clickhouse-green-1:
    <<: *clickhouse-defaults
    container_name: clickhouse-green-1
    hostname: clickhouse-green-1
    ports:
      - 9002:9000
      - 8125:8123
      - 9183:9181
    volumes:
      - "/clickhousedb-data/clickhouse-green-1/dataDir:/var/lib/clickhouse"
      - "./configs/gen/clickhouse-green-1:/etc/clickhouse-server/config.d/"

  clickhouse-green-2:
    <<: *clickhouse-defaults
    container_name: clickhouse-green-2
    hostname: clickhouse-green-2
    ports:
      - 9003:9000
      - 8126:8123
      - 9184:9181
    volumes:
      - "/clickhousedb-data/clickhouse-green-2/dataDir:/var/lib/clickhouse"
      - "./configs/gen/clickhouse-green-2:/etc/clickhouse-server/config.d/"

  # clickhouse-orange-1:
  #   <<: *clickhouse-defaults
  #   container_name: clickhouse-orange-1
  #   hostname: clickhouse-orange-1
  #   ports:
  #     - 9004:9000
  #     - 8127:8123
  #     - 9185:9181
  #   volumes:
  #     - "/clickhousedb-data/clickhouse-orange-1/dataDir:/var/lib/clickhouse"
  #     - "./configs/gen/clickhouse-orange-1:/etc/clickhouse-server/config.d/"

  # clickhouse-orange-2:
  #   <<: *clickhouse-defaults
  #   container_name: clickhouse-orange-2
  #   hostname: clickhouse-orange-2
  #   ports:
  #     - 9005:9000
  #     - 8128:8123
  #     - 9186:9181
  #   volumes:
  #     - "/clickhousedb-data/clickhouse-orange-2/dataDir:/var/lib/clickhouse"
  #     - "./configs/gen/clickhouse-orange-2:/etc/clickhouse-server/config.d/"
